name: Silver Adventure

on:
  workflow_dispatch:
  schedule:
    - cron: '0,3 * * * *' 

jobs:
  silver-adventure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Dependencies
        run: npm install

      - name: Run Stealth Bot
        run: node hsilver.js
